package com.trilogyed.stwitter.controller;

import com.trilogyed.stwitter.domain.Post;
import com.trilogyed.stwitter.service.ServiceLayer;
import com.trilogyed.stwitter.util.messages.Comment;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@RestController
public class StwitterController {

    public static final String EXCHANGE_NAME = "comment-exchange";
    public static final String ROUTING_KEY = "comment.create.#";

    @Autowired
    private RabbitTemplate rabbitTemplate;

    ServiceLayer service;

    public StwitterController(RabbitTemplate rabbitTemplate, ServiceLayer service) {
        this.rabbitTemplate = rabbitTemplate;
        this.service = service;
    }

    @PostMapping(value = "/posts")
    @ResponseStatus(value = HttpStatus.CREATED)
    public Post createPost(@RequestBody Post post) {
        List<String> commentsList = post.getComments();
        for(String c : commentsList) {
            System.out.println("Sending message...");
            rabbitTemplate.convertAndSend(EXCHANGE_NAME, ROUTING_KEY, c);
        }
        return post;
        //return service.addPost(post);
    }

//    @GetMapping(value="/posts/{id}")
//    @ResponseStatus(value=HttpStatus.OK)
//    public Post getPostById(@PathVariable int id) {
//
//    }
//
//    @GetMapping(value="/posts/user/{poster_name}")
//    @ResponseStatus(value=HttpStatus.OK)
//    public List<Post> getPostsByPosterName(@PathVariable(name="poster_name") String posterName) {
//
//    }



    //public static final String EXCHANGE = "queue-demo-exchange";
    //    public static final String ROUTING_KEY = "email.list.add.account.controller";
    //
    //    @Autowired
    //    private RabbitTemplate rabbitTemplate;
    //
    //    public AccountController(RabbitTemplate rabbitTemplate) {
    //        this.rabbitTemplate = rabbitTemplate;
    //    }
    //
    //    @RequestMapping(value = "/account", method = RequestMethod.POST)
    //    public String createAccount(@RequestBody Account account) {
    //        // create message to send to email list creation queue
    //        EmailListEntry msg = new EmailListEntry(account.getFirstName() + " " + account.getLastName(), account.getEmail());
    //        System.out.println("Sending message...");
    //        rabbitTemplate.convertAndSend(EXCHANGE, ROUTING_KEY, msg);
    //        System.out.println("Message Sent");
    //
    //        // Now do account creation stuff...
    //
    //        return "Account Created";
    //    }

    //Create Post
    //===========
    //URI: /posts
    //HTTP Method: POST
    //RequestBody: Post data (minus ID)
    //ResponseBody: Post data (including autogenerated ID)
    //
    //Get Post
    //========
    //URI: /posts/{id}
    //HTTP Method: GET
    //RequestBody: None
    //ResponseBody: Post data
    //
    //Get Posts for Poster
    //====================
    //URI: /posts/user/{poster_name}
    //HTTP Method: GET
    //RequestBody: None
    //ResponseBody: Array of Post data
}
