openapi: 3.0.0
info:
  title: Day Converter
  version: 0.0.1
  description: A service that converts a number to the name of a day.
servers: 
  - url: http://localhost:8080
    description: local development server
paths:
  /day/{dayNumber}:
    get:
      summary: Retrieves a number.
      parameters: 
        - name: dayNumber
          in: path
          required: true
          description: ID of the day you would like to retrieve.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: the name of a day from the number you put
          content:
             application/json:
              schema:
                type: string
        '400':
          description: Input is out of range.
