openapi: 3.0.0
info:
  title: Hello, REST
  description: A simple service that says Hello.
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: local development server
paths:
  /hello/{name}:
    get:
      summary: Retrieves a name.
      parameters: 
        - name: name
          in: path
          required: true
          description: name you would like to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: the string you sent to the service
          content:
            application/json:
              schema:
                type: string
                
      