openapi: 3.0.0
info:
  title: Quote API
  description: Random quote API.
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: local development server
paths:
  /quote:
    get:
      summary: Gets a random quote.
      responses:
        '200':
          description: Returns a random quote.
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Quote'
        
components:
  schemas:
    Quote:
      properties:
        author:
          type: string
        quote:
          type: string
      required: 
        - author
        - quote
        
        
                
      
        
                
      