openapi: 3.0.0
info:
  title: Word API
  description: Learn a word and its definition API.
  version: 0.0.1
servers: 
  - url: http://localhost:8080
    description: local development server
paths:
  /word:
    get:
      summary: Gets a random word and its definition.
      responses:
        '200':
          description: Returns a word and its definition.
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Definition'
        
components:
  schemas:
    Definition:
      properties:
        word:
          type: string
        definition:
          type: string
      required: 
        - word
        - definition
        
        
                
      
        
                
      